### PR TITLE
[EC-402] Azure DevOps pipelines migrated into GitHub Actions 

### PR DESCRIPTION
**Pull request by mamu0**
#### List of Changes

The two workflows on Azure DevOps

- `code-review`
- `deploy-pipelines`

have been recreated in the form of GitHub Actions, but `deploy-pipelines` is now divided into two actions one for the web app deploy on azure and one for npm publish sdk.

They have been inserted in the `.github/workflows` folder.

Added `pre-commit` configuration.

Added `infra` folder with `identity` and `repository` infrastructure, and added branch protection on `master` (already applied).

Edited `.gitignore` and `CODEOWNER` files.

#### Motivation and Context

Since all the pipelines on Azure DevOps are gradually being decommissioned, it was decided to recreate them on the different repos such as GitHub Actions.

#### How Has This Been Tested?

Currently they have been tested by inserting

```
push:
  branches:
    - EC-402-devops-decommissioning
```
so as to execute them automatically at each test push.
To do the Deploy test for `deploy-pipelines` action i've used this step only to check if all will be called correctly:
```
      - name: Deploy
        run: |
          az webapp up \
            --dryrun \
            --resource-group ${{ inputs.resource_group_name }} \
            --name ${{ inputs.app_name }} \
```

To do the Deploy test for `publish-sdk` action i've executed everything except last command with effective publish.

#### Types of changes

- [ ] Chore (nothing changes by a user perspective)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

#### Checklist:

- [ ] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by michaeldisaro** [comment]
This PR is not required anymore. These functions are inside, and deployed from, the `io-messages` monorepo.

**Comment by mamu0** [comment]
> This PR is not required anymore. These functions are inside, and deployed from, the `io-messages` monorepo.

So can I delete the `.devops` folder and change the PR to "_Repository alignment to new structure_"? (That is with the `infra` folder etc.)

**Comment by michaeldisaro** [comment]
I think we can just close this PR, and after the next days switch we can archive the repository.

**Comment by michaeldisaro** [comment]
We need the master of this repo to remain as it is.

**Comment by mamu0** [comment]
> We need the master of this repo to remain as it is.

If the **GitHub Action** part is not needed, the `Infra` folder with the terraform resources has been added anyway to align the repo with the structure we are adopting on all repos. What I meant was to remove the pipeline part if it does not need to be changed, but to leave the new tree structure, which is not a breaking change anyway.

**Comment by michaeldisaro** [comment]
> > We need the master of this repo to remain as it is.
> 
> If the **GitHub Action** part is not needed, the `Infra` folder with the terraform resources has been added anyway to align the repo with the structure we are adopting on all repos. What I meant was to remove the pipeline part if it does not need to be changed, but to leave the new tree structure, which is not a breaking change anyway.

Not a problem, but pretty a useless thing for a repo that will be archived soon, no? Anyway, I'll let you choose. :)

**Pull request closed without merging**
